server:
  port: 8080

spring:
  application:
    name: web-examples
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moyu
    username: root
    password: 123456

logging:
  level:
    com:
      moyu:
        examples:
          mapper: debug


moyu:
  swagger:
    title: ${spring.application.name}
    version: 1.0.0
    description: demo
    auth-enable: true
    api-prefix: /api/**

mybatis:
  mapper-locations: classpath:mapper/*


