server:
  port: 8080


spring:
  application:
    name: web-examples
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.default.svc.cluster.local:3306/admin-template
    username: root
    password: 8vB5Unc28z
  flyway:
    enabled: true

logging:
  level:
    com:
      moyu:
        examples:
          mapper: debug

framework:
  web:
    cors:
      enable: true
      allowed-headers: [ '*' ]
      allowed-methods: [ '*' ]
      allowed-origins: [ '*' ]
      max-age: 3600
  swagger:
    title: web-examples
    description: web-examples
    version: 1.0.0




mybatis:
  mapper-locations: classpath:mapper/*

