server:
  port: 8080

spring:
  application:
    name: web-examples
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo
    username: sa
    password:
  sql:
    init:
      platform: h2
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
      encoding: utf-8

logging:
  level:
    com:
      moyu:
        examples:
          mapper: debug


web:
  enable-rest-wrapper: true
  cors:
    enable: true
    allowed-headers: [ '*' ]
    allowed-methods: [ '*' ]
    allowed-origins: [ '*' ]
    max-age: 3600



mybatis:
  mapper-locations: classpath:mapper/*


