server:
  port: 8080

spring:
  application:
    name: web-examples
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: root
    password: 123456

logging:
  level:
    com:
      moyu:
        examples:
          mapper: debug


moyu:
  web:
    enable-rest-wrapper: true
    cors:
      enable: false
      allowed-headers: [ '*' ]
      allowed-methods: [ '*' ]
      allowed-origins: [ '*' ]
      max-age: 3600


mybatis:
  mapper-locations: classpath:mapper/*


